function I_drone_num = AutoFunc_sym_I_drone(alpha_arm_val)
%AutoFunc_sym_I_drone
%    I_drone_num = AutoFunc_sym_I_drone(ALPHA_ARM_VAL)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Aug-2025 19:04:12

t2 = sin(alpha_arm_val);
t3 = t2.^2;
t4 = t3.*1.2e+3;
t5 = t3.*(2.0./7.5e+1);
t6 = t4+9.61e+2;
t7 = sqrt(t6);
t8 = (t2.*t7)./1.5e+3;
t9 = t5+t8+4.602222222222222e-2;
I_drone_num = reshape([t9,0.0,0.0,0.0,t9,0.0,0.0,0.0,t9],[3,3]);
end
