function [J_rotor_full_num,J_rotor_flat_closed_num,J_rotor_flat_opened_num] = AutoFunc_sym_Mixer(alpha_arm_val)
%AutoFunc_sym_Mixer
%    [J_rotor_full_num,J_rotor_flat_closed_num,J_rotor_flat_opened_num] = AutoFunc_sym_Mixer(ALPHA_ARM_VAL)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Aug-2025 19:04:12

t2 = cos(alpha_arm_val);
t3 = sin(alpha_arm_val);
t4 = t2.^2;
t5 = t3.^2;
t6 = -t2;
t7 = -t3;
t8 = t2.*(3.0./4.0e+1);
t9 = t3./1.0e+1;
t10 = t3.*(3.0./4.0e+1);
t12 = t2./2.0e+2;
t15 = t3./2.0e+2;
t16 = t2.*(1.1e+1./1.0e+2);
t18 = t3.*(1.1e+1./1.0e+2);
t28 = t2.*t3.*(-1.0./1.0e+1);
t11 = -t8;
t13 = -t9;
t14 = -t10;
t17 = -t12;
t19 = -t15;
t20 = t4.*1.2e+3;
t21 = t5./1.0e+1;
t22 = t5.*1.2e+3;
t23 = t2.*t9;
t24 = -t16;
t25 = -t18;
t26 = -t20;
t27 = -t21;
t29 = t22+9.61e+2;
t30 = t26+2.161e+3;
t31 = sqrt(t29);
t32 = sqrt(t30);
t33 = t31./2.0e+2;
t35 = t15.*t31;
t37 = t3.*t31.*(-1.0./2.0e+2);
t34 = -t33;
t36 = t12.*t32;
t38 = t2.*t32.*(-1.0./2.0e+2);
t39 = t9+t33+1.0./2.0e+2;
t43 = t16+t19+t27+t37;
t44 = t19+t24+t27+t37;
t40 = t13+t34-1.0./2.0e+2;
t41 = t12+t18+t23+t36;
t42 = t12+t23+t25+t36;
J_rotor_full_num = reshape([0.0,t7,t2,0.0,t17+t18+t28+t38,t44,t3,0.0,t2,t41,0.0,t43,0.0,t3,t2,0.0,t42,t44,t7,0.0,t2,t17+t25+t28+t38,0.0,t43,0.0,t2,t3,0.0,t43,t41,t6,0.0,t3,t15+t16+t21+t35,0.0,t42,0.0,t6,t3,0.0,t15+t21+t24+t35,t41,t2,0.0,t3,t44,0.0,t42],[6,8]);
if nargout > 1
    J_rotor_flat_closed_num = reshape([0.0,0.0,1.0,t14,t40,-1.1e+1./1.0e+2,0.0,0.0,1.0,t39,t14,1.1e+1./1.0e+2,0.0,0.0,1.0,t10,t39,-1.1e+1./1.0e+2,0.0,0.0,1.0,t40,t10,1.1e+1./1.0e+2],[6,4]);
end
if nargout > 2
    J_rotor_flat_opened_num = reshape([0.0,0.0,1.0,t8,t40,-1.1e+1./1.0e+2,0.0,0.0,1.0,t39,t8,1.1e+1./1.0e+2,0.0,0.0,1.0,t11,t39,-1.1e+1./1.0e+2,0.0,0.0,1.0,t40,t11,1.1e+1./1.0e+2],[6,4]);
end
end
