function cf_c = AutoFunc_sym_c_wf_c(yaw_sym,w1,w2,in4,in5)
%AutoFunc_sym_c_wf_c
%    CF_C = AutoFunc_sym_c_wf_c(YAW_SYM,W1,W2,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Aug-2025 19:04:14

pinv_Mixer_augmented_11 = in5(1);
pinv_Mixer_augmented_12 = in5(9);
pinv_Mixer_augmented_13 = in5(17);
pinv_Mixer_augmented_21 = in5(2);
pinv_Mixer_augmented_22 = in5(10);
pinv_Mixer_augmented_23 = in5(18);
pinv_Mixer_augmented_31 = in5(3);
pinv_Mixer_augmented_32 = in5(11);
pinv_Mixer_augmented_33 = in5(19);
pinv_Mixer_augmented_41 = in5(4);
pinv_Mixer_augmented_42 = in5(12);
pinv_Mixer_augmented_43 = in5(20);
pinv_Mixer_augmented_51 = in5(5);
pinv_Mixer_augmented_52 = in5(13);
pinv_Mixer_augmented_53 = in5(21);
pinv_Mixer_augmented_61 = in5(6);
pinv_Mixer_augmented_62 = in5(14);
pinv_Mixer_augmented_63 = in5(22);
pinv_Mixer_augmented_71 = in5(7);
pinv_Mixer_augmented_72 = in5(15);
pinv_Mixer_augmented_73 = in5(23);
pinv_Mixer_augmented_81 = in5(8);
pinv_Mixer_augmented_82 = in5(16);
pinv_Mixer_augmented_83 = in5(24);
t2 = cos(yaw_sym);
t3 = sin(yaw_sym);
t4 = pinv_Mixer_augmented_11.*pinv_Mixer_augmented_23.*t2;
t5 = pinv_Mixer_augmented_13.*pinv_Mixer_augmented_21.*t2;
t6 = pinv_Mixer_augmented_12.*pinv_Mixer_augmented_23.*t3;
t7 = pinv_Mixer_augmented_13.*pinv_Mixer_augmented_22.*t3;
t8 = -t5;
t9 = -t7;
t10 = t4+t6+t8+t9;
t11 = 1.0./t10;
mt1 = [t11.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_33.*t2.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_31.*t2.*w1+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_33.*t3.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_32.*t3.*w1-pinv_Mixer_augmented_21.*pinv_Mixer_augmented_33.*t2.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_31.*t2.*w2-pinv_Mixer_augmented_22.*pinv_Mixer_augmented_33.*t3.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_32.*t3.*w2)-t11.*w1.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_33.*t2-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_31.*t2+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_33.*t3-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_32.*t3)+t11.*w2.*(pinv_Mixer_augmented_21.*pinv_Mixer_augmented_33.*t2-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_31.*t2+pinv_Mixer_augmented_22.*pinv_Mixer_augmented_33.*t3-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_32.*t3)];
mt2 = [t11.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_43.*t2.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_41.*t2.*w1+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_43.*t3.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_42.*t3.*w1-pinv_Mixer_augmented_21.*pinv_Mixer_augmented_43.*t2.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_41.*t2.*w2-pinv_Mixer_augmented_22.*pinv_Mixer_augmented_43.*t3.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_42.*t3.*w2)-t11.*w1.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_43.*t2-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_41.*t2+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_43.*t3-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_42.*t3)+t11.*w2.*(pinv_Mixer_augmented_21.*pinv_Mixer_augmented_43.*t2-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_41.*t2+pinv_Mixer_augmented_22.*pinv_Mixer_augmented_43.*t3-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_42.*t3)];
mt3 = [t11.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_53.*t2.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_51.*t2.*w1+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_53.*t3.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_52.*t3.*w1-pinv_Mixer_augmented_21.*pinv_Mixer_augmented_53.*t2.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_51.*t2.*w2-pinv_Mixer_augmented_22.*pinv_Mixer_augmented_53.*t3.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_52.*t3.*w2)-t11.*w1.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_53.*t2-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_51.*t2+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_53.*t3-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_52.*t3)+t11.*w2.*(pinv_Mixer_augmented_21.*pinv_Mixer_augmented_53.*t2-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_51.*t2+pinv_Mixer_augmented_22.*pinv_Mixer_augmented_53.*t3-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_52.*t3)];
mt4 = [t11.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_63.*t2.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_61.*t2.*w1+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_63.*t3.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_62.*t3.*w1-pinv_Mixer_augmented_21.*pinv_Mixer_augmented_63.*t2.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_61.*t2.*w2-pinv_Mixer_augmented_22.*pinv_Mixer_augmented_63.*t3.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_62.*t3.*w2)-t11.*w1.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_63.*t2-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_61.*t2+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_63.*t3-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_62.*t3)+t11.*w2.*(pinv_Mixer_augmented_21.*pinv_Mixer_augmented_63.*t2-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_61.*t2+pinv_Mixer_augmented_22.*pinv_Mixer_augmented_63.*t3-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_62.*t3)];
mt5 = [t11.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_73.*t2.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_71.*t2.*w1+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_73.*t3.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_72.*t3.*w1-pinv_Mixer_augmented_21.*pinv_Mixer_augmented_73.*t2.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_71.*t2.*w2-pinv_Mixer_augmented_22.*pinv_Mixer_augmented_73.*t3.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_72.*t3.*w2)-t11.*w1.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_73.*t2-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_71.*t2+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_73.*t3-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_72.*t3)+t11.*w2.*(pinv_Mixer_augmented_21.*pinv_Mixer_augmented_73.*t2-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_71.*t2+pinv_Mixer_augmented_22.*pinv_Mixer_augmented_73.*t3-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_72.*t3)];
mt6 = [t11.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_83.*t2.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_81.*t2.*w1+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_83.*t3.*w1-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_82.*t3.*w1-pinv_Mixer_augmented_21.*pinv_Mixer_augmented_83.*t2.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_81.*t2.*w2-pinv_Mixer_augmented_22.*pinv_Mixer_augmented_83.*t3.*w2+pinv_Mixer_augmented_23.*pinv_Mixer_augmented_82.*t3.*w2)-t11.*w1.*(pinv_Mixer_augmented_11.*pinv_Mixer_augmented_83.*t2-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_81.*t2+pinv_Mixer_augmented_12.*pinv_Mixer_augmented_83.*t3-pinv_Mixer_augmented_13.*pinv_Mixer_augmented_82.*t3)+t11.*w2.*(pinv_Mixer_augmented_21.*pinv_Mixer_augmented_83.*t2-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_81.*t2+pinv_Mixer_augmented_22.*pinv_Mixer_augmented_83.*t3-pinv_Mixer_augmented_23.*pinv_Mixer_augmented_82.*t3)];
cf_c = [mt1;mt2;mt3;mt4;mt5;mt6];
end
