function [Mt_num,C_num] = AutoFunc_sym_function_drone(in1,in2,alpha_arm_val)
%AutoFunc_sym_function_drone
%    [Mt_num,C_num] = AutoFunc_sym_function_drone(IN1,IN2,ALPHA_ARM_VAL)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Aug-2025 19:04:11

dy4 = in2(4,:);
dy5 = in2(5,:);
dy6 = in2(6,:);
y5 = in1(5,:);
t2 = sin(alpha_arm_val);
t3 = cos(y5);
t4 = sin(y5);
t5 = t2.^2;
t6 = t5.*1.2e+3;
t7 = t5.*(2.0./7.5e+1);
t10 = t5.*2.882303761517117e+19;
t8 = t6+9.61e+2;
t9 = sqrt(t8);
t11 = (t2.*t9)./1.5e+3;
t12 = t2.*t9.*7.205759403792794e+17;
t13 = t7+t11+4.602222222222222e-2;
t14 = t10+t12+4.974375908418292e+19;
t15 = (t4.*t14)./1.080863910568919e+21;
t16 = -t15;
Mt_num = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,t13,0.0,t16,0.0,0.0,0.0,0.0,t13,0.0,0.0,0.0,0.0,t16,0.0,t13],[6,6]);
if nargout > 1
    C_num = [0.0;0.0;9.806649999999999;dy5.*dy6.*t3.*t14.*(-9.251858538542971e-22);(dy4.*dy6.*t3.*t14)./1.080863910568919e+21;dy4.*dy5.*t3.*t14.*(-9.251858538542971e-22)];
end
end
