function l_face_num = AutoFunc_sym_l_face(alpha_arm_val)
%AutoFunc_sym_l_face
%    L_FACE_NUM = AutoFunc_sym_l_face(ALPHA_ARM_VAL)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    22-Aug-2025 19:04:12

t2 = sin(alpha_arm_val);
l_face_num = t2./1.0e+1+sqrt(t2.^2.*1.2e+3+9.61e+2)./2.0e+2;
end
