function J_rotor_num = AutoFunc_sym_Mixer(alpha_arm)
%AutoFunc_sym_Mixer
%    J_rotor_num = AutoFunc_sym_Mixer(ALPHA_ARM)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:04

t2 = cos(alpha_arm);
t3 = sin(alpha_arm);
t4 = sqrt(3.0);
t5 = t3./2.0;
t6 = t2.*(7.0./2.0e+1);
t7 = t2.*(7.0./4.0e+1);
t9 = t3.*(7.0./2.0e+1);
t12 = t2.*(1.1e+1./1.0e+2);
t13 = t3.*(1.1e+1./1.0e+2);
t14 = t3.*(1.1e+1./2.0e+2);
t19 = t3.*t4.*(-1.0./2.0);
t20 = t2.*t4.*(-7.0./4.0e+1);
t22 = t3.*t4.*(-1.1e+1./2.0e+2);
t8 = -t5;
t10 = -t7;
t11 = -t9;
t15 = -t12;
t16 = -t14;
t17 = t4.*t5;
t18 = t4.*t7;
t21 = t4.*t14;
t23 = t9+t12;
t24 = t10+t14;
t25 = t7+t16;
t26 = t11+t15;
t27 = t20+t21;
t28 = t18+t22;
J_rotor_num = reshape([t3,0.0,t2,t6-t13,0.0,t26,t8,t19,t2,t25,t28,t23,t8,t17,t2,t24,t28,t26,t3,0.0,t2,-t6+t13,0.0,t23,t8,t19,t2,t24,t27,t26,t8,t17,t2,t25,t27,t23],[6,6]);
end
