function out1 = AutoFunc_sym_F3_trans_h(alpha,Fz,w1,w2)
%AutoFunc_sym_F3_trans_h
%    OUT1 = AutoFunc_sym_F3_trans_h(ALPHA,Fz,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(alpha);
out1 = ((Fz.*-3.0+t2.*w1.*6.0+t2.*w2.*6.0).*(-1.0./6.0))./t2;
end
