function Fb_test_w2 = AutoFunc_sym_Fb_trans_w2(alpha,yaw,w1,w2)
%AutoFunc_sym_Fb_trans_w2
%    Fb_test_w2 = AutoFunc_sym_Fb_trans_w2(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(yaw);
t5 = sin(yaw);
t7 = sqrt(3.0);
t6 = t5.*w2;
t8 = t5.*w1.*2.0;
t10 = t4.*t7;
t9 = -t6;
t11 = t10.*w2;
t12 = t5+t10;
t13 = 1.0./t12;
t14 = t8+t9+t11;
Fb_test_w2 = [t3.*w1.*2.0-t3.*w2-t3.*t13.*t14;-t3.*t7.*w2+t3.*t7.*t13.*t14;t2.*w1.*2.0+t2.*w2.*2.0+t2.*t13.*t14.*2.0;0.0;0.0;0.0];
end
