function c3_w2 = AutoFunc_sym_c3_w2(alpha,yaw,w1,w2)
%AutoFunc_sym_c3_w2
%    C3_W2 = AutoFunc_sym_c3_w2(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(yaw);
t3 = sin(yaw);
t4 = sqrt(3.0);
t5 = t2.*t4;
t6 = t3+t5;
t7 = 1.0./t6;
c3_w2 = t7.*(t3.*w1.*2.0-t3.*w2+t5.*w2)-t3.*t7.*w1.*2.0+t7.*w2.*(t3-t5);
end
