function out1 = AutoFunc_sym_F3_trans_w2(alpha,yaw,w1,w2)
%AutoFunc_sym_F3_trans_w2
%    OUT1 = AutoFunc_sym_F3_trans_w2(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(yaw);
t3 = sin(yaw);
t4 = sqrt(3.0);
out1 = (t3.*w1.*2.0-t3.*w2+t2.*t4.*w2)./(t3+t2.*t4);
end
