function k3x_w2 = AutoFunc_sym_k3x_w2(alpha,yaw,w1,w2)
%AutoFunc_sym_k3x_w2
%    K3X_W2 = AutoFunc_sym_k3x_w2(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = sin(yaw);
k3x_w2 = (t2.*2.0)./(t2+sqrt(3.0).*cos(yaw));
end
