function Fb_test_w = AutoFunc_sym_Fb_trans_h(alpha,Fz,w1,w2)
%AutoFunc_sym_Fb_trans_h
%    Fb_test_w = AutoFunc_sym_Fb_trans_h(ALPHA,Fz,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(alpha);
t3 = sin(alpha);
t4 = Fz.*3.0;
t7 = sqrt(3.0);
t5 = -t4;
t6 = 1.0./t2;
t8 = t2.*w1.*6.0;
t9 = t2.*w2.*6.0;
t10 = t5+t8+t9;
Fb_test_w = [t3.*w1.*2.0-t3.*w2+(t3.*t6.*t10)./6.0;-t3.*t7.*w2-(t3.*t6.*t7.*t10)./6.0;Fz;0.0;0.0;0.0];
end
