function Fb_test_w3 = AutoFunc_sym_Fb_trans_w3(alpha,yaw,w1,w2)
%AutoFunc_sym_Fb_trans_w3
%    Fb_test_w3 = AutoFunc_sym_Fb_trans_w3(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(alpha);
t3 = sin(alpha);
t4 = cos(yaw);
t5 = sin(yaw);
t7 = sqrt(3.0);
t6 = t5.*w2;
t8 = t5.*w1.*2.0;
t10 = t4.*t7;
t9 = -t8;
t11 = t10.*w2;
t12 = -t10;
t13 = t5+t12;
t15 = t6+t9+t11;
t14 = 1.0./t13;
Fb_test_w3 = [t3.*w1.*2.0-t3.*w2+t3.*t14.*t15;t3.*t7.*w2+t3.*t7.*t14.*t15;t2.*w1.*2.0+t2.*w2.*2.0-t2.*t14.*t15.*2.0;0.0;0.0;0.0];
end
