function k3x_w3 = AutoFunc_sym_k3x_w3(alpha,yaw,w1,w2)
%AutoFunc_sym_k3x_w3
%    K3X_W3 = AutoFunc_sym_k3x_w3(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

k3x_w3 = 0.0;
end
