function c3 = AutoFunc_sym_c3_h(alpha,Fz,w1,w2)
%AutoFunc_sym_c3_h
%    C3 = AutoFunc_sym_c3_h(ALPHA,Fz,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(alpha);
c3 = w1+w2-(Fz.*-3.0+t2.*w1.*6.0+t2.*w2.*6.0)./(t2.*6.0);
end
