function [S_eta_num,dS_eta_num] = AutoFunc_S_eta_gen(in1,in2)
%AutoFunc_S_eta_gen
%    [S_eta_num,dS_eta_num] = AutoFunc_S_eta_gen(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:04

dy4 = in2(4,:);
dy5 = in2(5,:);
y4 = in1(4,:);
y5 = in1(5,:);
t2 = cos(y4);
t3 = cos(y5);
t4 = sin(y4);
t5 = sin(y5);
S_eta_num = reshape([1.0,0.0,0.0,0.0,t2,-t4,-t5,t3.*t4,t2.*t3],[3,3]);
if nargout > 1
    dS_eta_num = reshape([0.0,0.0,0.0,0.0,-dy4.*t4,-dy4.*t2,-dy5.*t3,dy4.*t2.*t3-dy5.*t4.*t5,-dy4.*t3.*t4-dy5.*t2.*t5],[3,3]);
end
end
