function k3y = AutoFunc_sym_k3y_h(alpha,Fz,w1,w2)
%AutoFunc_sym_k3y_h
%    K3Y = AutoFunc_sym_k3y_h(ALPHA,Fz,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

k3y = -1.0;
end
