function out1 = AutoFunc_sym_F3_trans_w3(alpha,yaw,w1,w2)
%AutoFunc_sym_F3_trans_w3
%    OUT1 = AutoFunc_sym_F3_trans_w3(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

out1 = w2;
end
