function k3y_w2 = AutoFunc_sym_k3y_w2(alpha,yaw,w1,w2)
%AutoFunc_sym_k3y_w2
%    K3Y_W2 = AutoFunc_sym_k3y_w2(ALPHA,YAW,W1,W2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    25-Aug-2025 11:22:05

t2 = cos(yaw);
t3 = sin(yaw);
t4 = sqrt(3.0);
t5 = t2.*t4;
k3y_w2 = -(t3-t5)./(t3+t5);
end
